### ISSUE TITLE
83.01 - Quimica

### ISSUE THREAD

**Issue by fadellavedova** [Apuntes-FIUBA/Apuntes-Electronica#4]
[Parcial 2-6-23 (resuelto).pdf](https://github.com/Apuntes-FIUBA/Apuntes-Electronica/files/12448800/Parcial.2-6-23.resuelto.pdf)

**Comment by igonzalezb** [comment]
Perfecto, ya lo agrego.

Gracias

**Comment by igonzalezb** [comment]
Perfecto, ya lo agrego.

Gracias
